Billing Account LockedAmount and ConsumedAmount update
topcoder-platform/tc-billing-account-service pull request #70
Opened 2023-08-08 09:46 UTC by sarojbehera1

2023-08-25 08:47 UTC, liuliquan requested changes
Need fix unit tests, make sure `mvn clean package integration-test` command success

2023-09-01 02:26 UTC, liuliquan requested changes

2023-09-01 02:26 UTC, liuliquan commented on service/src/main/java/com/appirio/service/billingaccount/manager/BillingAccountManager.java
> +        LoggerFactory.getLogger(BillingAccountManager.class).debug("Queried if "+requestedAmount +" can be locked. Result : "+(totalLockingAmount <= availableAmount));
The logger should be a private static final field, initialized only once, like this [logger](https://github.com/topcoder-platform/tc-billing-account-service/blob/dev/service/src/main/java/com/appirio/service/billingaccount/resources/BillingAccountResource.java#L69)

2023-09-01 02:26 UTC, liuliquan commented on service/src/main/java/com/appirio/service/billingaccount/manager/BillingAccountManager.java
> +        if ( requestedAmount > availableAmount) {
I'm a bit nervous for the sum/subtract of Float values, they will cause float precision error. For example:
``` 
System.out.println(90.9f - 60.6f > 30.3f); // should print false, but it prints true
```
Given only need 2 decimal points at max for the money amount, I suggest some tricks for the sum/subtract:
```
	private static Float sum(Float f1, Float f2) {
		return Math.round((f1 * 100 + f2 * 100)) / 100f;
	}
	private static Float subtract(Float f1, Float f2) {
		return Math.round((f1 * 100 - f2 * 100)) / 100f;
	}
```
Or may try using BigDecimal.

Also these new methods with float calculations should be unit tested.

2023-09-01 02:26 UTC, liuliquan commented on service/src/main/resources/sql/billing-account/update-locked-amount.sql
> +    project_id = :project_id;
Use incrementing add style for set clause, to prevent concurrent modification. E.g., pass in the requested amount and add it:

`SET locked_amount = locked_amount + :requested_amount`

2023-09-01 02:26 UTC, liuliquan commented on service/src/main/resources/sql/billing-account/update-consumed-amount.sql
> +    project_id = :project_id;
Use incrementing add style for set clause, to prevent concurrent modification. E.g., pass in the requested amount and add it:

`SET consumed_amount = consumed_amount + :requested_amount`

2023-09-01 02:26 UTC, liuliquan commented on service/src/main/java/com/appirio/service/billingaccount/manager/BillingAccountManager.java
> +        Float lockedAmount = billingAccount.getLockedAmount();
These amount retrieved from database could be null, in which case should use zero for the null.

2023-09-01 02:26 UTC, liuliquan commented on service/src/main/java/com/appirio/service/billingaccount/manager/BillingAccountManager.java
> +        List<BillingAccount> originals = getBillingAccount(billingAccountId).getData();
Need update get-billing-account-by-id.sql to get the new consumedAmount and lockedAmount column values

2023-09-06 03:38 UTC, liuliquan approved these changes

2023-09-06 12:34 UTC, rakibansary requested changes
Added a comment!

2023-09-06 12:34 UTC, rakibansary commented on service/src/main/java/com/appirio/service/billingaccount/resources/BillingAccountResource.java
> +            @Valid PostPutRequest<ConsumedAmountDTO> consumedAmountDTO) {
Let's add `challengeId: string` and `markup: float` to `ConsumedAmountDTO` - ideally these should be stored in DB for auditing, but we'll skip saving them to database for now and these values will only be used for publishing for now.

2023-11-07 12:11 UTC, merged